--- #YAML:1.0
name:               Parallel-Fork-BossWorker
version:            0.04
abstract:           Perl extension for easiliy creating forking queue processing applications.
author:
    - Jeff Rodriguez, Tim Wilde
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
